### ISSUE TITLE
Not all functions do work

### ISSUE THREAD

**Issue by brinkgit** [pbrunier/node-red-contrib-dyson-purelink#49]
Hello,

I try to use this node, but it seems functioning only partly. I have a Dyson Pure Cool.

If I try to set fan speed, it returns the actual fan-speed, but does not set a new fan speed
If I set rotaion on, it works, but setting rotation off does not work.

Do I do somethng wrong, or is the node not working 100%?

Regards G. Brink

Edit:
found the solution. Used function nodes with payload.action for all settings. Works good.
Speed setting: for example 3 needs to be set as speed 30. Then it works.

**Comment by pbrunier** [comment]
This project was archived for a while and I took over recently. Therefore it took a while to get back to you.
setFanSpeed is indeed implemented as a percentage. If you think this is an issue please reopen this issue.
Will close the issue for now.
