### ISSUE TITLE
Cannot setup OTP.  Getting Error 401 when I click the authenticate to use OTP button: 

### ISSUE THREAD

**Issue by etc6849** [pbrunier/node-red-contrib-dyson-purelink#50]
**Describe the bug**
Cannot setup OTP.  Getting Error 401 when I click the authenticate to use OTP button

msg : error
"Error: Request failed with status code 401"

**To Reproduce**
1. Add a new config account.
2. Click authenticate.

**Comment by pbrunier** [comment]
Please open the Dyson app on your phone when doing your steps. Having it open probably resolves your issue. Will implement a notice about this in a future version.

**Comment by pbrunier** [comment]
TODO: When configuring the config node, ask the user to open the Dyson App. This triggers the Dyson cloud to allow new device connections.
