### ISSUE TITLE
How to set temperature 

### ISSUE THREAD

**Issue by Neno83** [pbrunier/node-red-contrib-dyson-purelink#53]
hiii :)

I tried 

{"action":"setTemperature","temperature":"22"}

but this action is probably not implemented?
and also should get Celsius or Fahrenheit?
if not implemented? Will this be implemented?

thank you very much 
Neno

**Comment by pbrunier** [comment]
Hi Neno,

This project has been archived for a while and I took over recently. If you're still interested in a fix, please let me know what Dyson device you have. You're right about, that setTemperature isn't implemented. But I might be able to do this.

**Comment by Neno83** [comment]
Hi @pbrunier 

I tried to understand and add the piece of code but I didn’t have enough time to find out the correct command..

It would be cool if you will find out that and art setTemperature.

my Dyson model is:

Dyson Pure Hot+Cool Link™ (Weiss/Silber) HP02

https://www.dyson.ch/de_ch/support/journey/replacement-parts/search.305578-01?utm_medium=dyson_connect&utm_source=link_app&utm_campaign=contextual_menu_EU&link_sku=305578-01&utm_medium=dyson_connect&utm_source=link_app&utm_campaign=contextual_menu_CH&link_id=35f51858-9185-4fe8-89c9-b274e95f41ee&interaction_id=5E6A69EE-1A4E-4D7C-9537-01F2D48A95F4

**Comment by pbrunier** [comment]
I think we will manage to get it fixed. As I don't have the Dyson with heating I need a bit of your help. Can you send some screenshots from the Dyson app  and describe me the working of the heating function. Range, Celsius/Fahrenheit or adjustable, toggles, etc, etc.

**Comment by Neno83** [comment]
It would ne cool.

yes here the Screenshots.
![IMG_3269](https://github.com/pbrunier/node-red-contrib-dyson-purelink/assets/53298768/6e20fc2f-334d-459b-89f3-a96d4ad5a312)
![IMG_3270](https://github.com/pbrunier/node-red-contrib-dyson-purelink/assets/53298768/15dc2576-31cc-4b11-b61e-9d16d88c188d)
![IMG_3271](https://github.com/pbrunier/node-red-contrib-dyson-purelink/assets/53298768/9bb4cfe1-9e3b-41b2-9b36-98a95cc67612)
![IMG_3272](https://github.com/pbrunier/node-red-contrib-dyson-purelink/assets/53298768/aa41e67e-3323-47eb-9fa6-ab517f251cf9)
![IMG_3273](https://github.com/pbrunier/node-red-contrib-dyson-purelink/assets/53298768/2aa7b5ac-2c3d-4b01-a83a-6f1699b4f9db)
![IMG_3274](https://github.com/pbrunier/node-red-contrib-dyson-purelink/assets/53298768/a0906676-97a1-4197-91e1-4a8b9b6313f4)

**Comment by pbrunier** [comment]
Thank you. Will start looking into it soon. Luckily I'm from NL, so my DE is pretty ok 😄

**Comment by pbrunier** [comment]
@Neno83 It's not possible to set the temp to fractions of whole degrees, right? So only 25 or 26, but not 25.5?

**Comment by Neno83** [comment]
@pbrunier That’s true. Just steps (plus and minus) of 1°C “unfortunately”.

**Comment by pbrunier** [comment]
Hi @Neno83 ,

Sorry for the terrible delay. The past months were very busy, so I didn't manage to fix this issue.
I think, that I've fixed it the issue now. Can you give it a try? I don't have a Dyson with heating.

Two new node actions:
getTemperatureTarget
and
setTemperatureTarget where msg.payload.temperatureTarget must be set between 1 and 37

Please let me know how it goes. If something goes wrong pls add the output of the also new action getDeviceInfo in this issue, so I can follow up. 
If you have other suggestions regarding parameters names etc, pls let me know. I can change it, since you will probably be the first user ;)
Thanks!

**Comment by Neno83** [comment]
Hi @pbrunier 
Thank you for the message and changes.

I updated my Node-Red and tried these functions.

1)
I set temp to 22 Celsius and on Device saw it set 1 Celsius. 
- and Node-red stops working, (Stopped) I have to start the Node-Red server.

2)
I then tired to send 72 fahrenheit instead of 22, but not working.
- I get this error:

1/3/2024, 11:50:33 AM[node: Dyson Neno](http://192.168.1.225/addons/red/#)
msg : error
"TypeError: Cannot read property 'then' of undefined"

3)
By getTemperatureTarget I don't get the temperature back instead Node-red stops again.

4)
Device Info:

{"deviceInfo":{"productType":"455","state":{"fmod":"FAN","fnst":"FAN","fnsp":"0001","qtar":"0003","oson":"OFF","rhtm":"ON","filf":"2794","ercd":"NONE","nmod":"OFF","wacd":"NONE","hmod":"HEAT","hmax":"2970","hsta":"HEAT","ffoc":"ON","tilt":"OK"}}}

5) 
Node-red Dubug:

setTemperatureTarget

...
Jan  3 11:58:15 ccu3-webui daemon.debug node-red[27701]: [dyson-link:Dyson Neno] action: setTemperatureTarget
Jan  3 11:58:15 ccu3-webui daemon.debug node-red[27701]: [ccu-connection:localhost]     < BidCos-RF getLinks []
Jan  3 11:58:15 ccu3-webui daemon.info node-red[27701]: [ccu-connection:localhost] regadata saved to /usr/local/addons/redmatic/var/ccu_rega_localhost.json
Jan  3 11:58:15 ccu3-webui daemon.err node-red: 3 Jan 11:58:15 - [red] Uncaught Exception:
Jan  3 11:58:15 ccu3-webui daemon.err node-red: 3 Jan 11:58:15 - TypeError: Cannot read property 'hmax' of undefined
Jan  3 11:58:15 ccu3-webui daemon.err node-red:     at Device.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/dist/dysonpurelink/device.js:349:71)
Jan  3 11:58:15 ccu3-webui daemon.err node-red:     at Object.onceWrapper (events.js:422:26)
Jan  3 11:58:15 ccu3-webui daemon.err node-red:     at Device.emit (events.js:315:20)
Jan  3 11:58:15 ccu3-webui daemon.err node-red:     at MqttClient.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/dist/dysonpurelink/device.js:151:27)
Jan  3 11:58:15 ccu3-webui daemon.err node-red:     at MqttClient.emit (events.js:315:20)
Jan  3 11:58:15 ccu3-webui daemon.err node-red:     at MqttClient._handlePublish (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/node_modules/mqtt/lib/client.js:1541:12)
Jan  3 11:58:15 ccu3-webui daemon.err node-red:     at MqttClient._handlePacket (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/node_modules/mqtt/lib/client.js:529:12)
Jan  3 11:58:15 ccu3-webui daemon.err node-red:     at work (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/node_modules/mqtt/lib/client.js:430:12)
Jan  3 11:58:15 ccu3-webui daemon.err node-red:     at Writable.writable._write (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/node_modules/mqtt/lib/client.js:444:5)
Jan  3 11:58:15 ccu3-webui daemon.err node-red:     at doWrite (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/node_modules/readable-stream/lib/_stream_writable.js:390:139)
Jan  3 11:58:15 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 1
...


getTemperatureTarget

...
Jan  3 12:00:48 ccu3-webui daemon.debug node-red[28805]: [dyson-link:Dyson Neno] action: getTemperatureTarget
Jan  3 12:00:48 ccu3-webui daemon.err node-red: 3 Jan 12:00:48 - [red] Uncaught Exception:
Jan  3 12:00:48 ccu3-webui daemon.err node-red: 3 Jan 12:00:48 - TypeError: Cannot read property 'hmax' of undefined
Jan  3 12:00:48 ccu3-webui daemon.err node-red:     at Device.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/dist/dysonpurelink/device.js:349:71)
Jan  3 12:00:48 ccu3-webui daemon.err node-red:     at Object.onceWrapper (events.js:422:26)
Jan  3 12:00:48 ccu3-webui daemon.err node-red:     at Device.emit (events.js:315:20)
Jan  3 12:00:48 ccu3-webui daemon.err node-red:     at MqttClient.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/dist/dysonpurelink/device.js:151:27)
Jan  3 12:00:48 ccu3-webui daemon.err node-red:     at MqttClient.emit (events.js:315:20)
Jan  3 12:00:48 ccu3-webui daemon.err node-red:     at MqttClient._handlePublish (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/node_modules/mqtt/lib/client.js:1541:12)
Jan  3 12:00:48 ccu3-webui daemon.err node-red:     at MqttClient._handlePacket (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/node_modules/mqtt/lib/client.js:529:12)
Jan  3 12:00:48 ccu3-webui daemon.err node-red:     at work (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/node_modules/mqtt/lib/client.js:430:12)
Jan  3 12:00:48 ccu3-webui daemon.err node-red:     at Writable.writable._write (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/node_modules/mqtt/lib/client.js:444:5)
Jan  3 12:00:48 ccu3-webui daemon.err node-red:     at doWrite (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-dyson-purelink/node_modules/readable-stream/lib/_stream_writable.js:390:139)
Jan  3 12:00:48 ccu3-webui daemon.err node-red: Node-RED exited with non-zero exit status 1
Jan  3 12:00:48 ccu3-webui daemon.warn redmatic: Restarting Node-RED (2/2147483647)
...

**Comment by pbrunier** [comment]
Sorry for the inconvenience. 0.8.1 should fix both issues.  Will be in the catalogue in a few hours.
Thanks for your feedback.

**Comment by Neno83** [comment]
Hi @pbrunier 
Thx! **Great job!!!**

I tried and I don't get any error anymore, the temperature is set on the device:

1) Set Temp
**{"action":"setTemperatureTarget","temperatureTarget": 27}**

2) get Temp
{"temperatureTarget":27}

3) Get Info
{"deviceInfo":{"productType":"455","state":{"fmod":"FAN","fnst":"OFF","fnsp":"0001","qtar":"0003","oson":"OFF","rhtm":"ON","filf":"2794","ercd":"NONE","nmod":"OFF","wacd":"NONE","hmod":"HEAT","hmax":"2960","hsta":"OFF","ffoc":"ON","tilt":"OK"}}}


Thank you very much!!!
Now I can  finally create my Apple Home rules to automatically manage the Dyson over Node-red on my Homematic CCU3!

Have a nice day
Neno

**Comment by pbrunier** [comment]
@Neno83 Your welcome
