### ISSUE TITLE
Flowdirection should be controllable

### ISSUE THREAD

**Issue by user231231** [pbrunier/node-red-contrib-dyson-purelink#74]
I realy love the module and it works well for me so far.

Only issue I expericened is that I am not able to controll the Flowdirection of my purifyier.

Via DysonApp the Flowdirection allows me to change between a direkt airstream (ventilation/cooling) and a diffuse one (just cleaning).

I'd realy appreciate if this control is added in the module, or am I missing an opportunity to contoll it already?

Cheers, 
Michael

**Comment by pbrunier** [comment]
@user231231 

This one has been fixed now in release 0.7.0
Should be available soon in the Node-RED node overview so you can update it.

Three new actions have been implemented: setJetFocusOn, setJetFocusOff, getJetFocus
